class FileStoreParam(object):
    FILE_ID = "file_id"
    FILE_NAME = "name"
    FILE_SIZE = "size"
    FILE_HASH = "hash"
    FILE_SEGMENT_NUMBER = "segment_number"
    FILE_SEGMENTS_RECEIVED = "segments_received"
    FILE_COMPLETE = "complete"
    FILE_CANCEL = "cancel"
    FILE_STORE = "store"
